<?xml version="1.0" encoding="UTF-8"?>
<definitions name="Camelizer" xmlns:typens="urn:ActionWebService" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="urn:ActionWebService" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <message name="Camelize">
    <part name="string" type="xsd:string"/>
  </message>
  <message name="CamelizeResponse">
    <part name="return" type="xsd:string"/>
  </message>
  <portType name="CamelizerCamelizerPort">
    <operation name="Camelize">
      <input message="typens:Camelize"/>
      <output message="typens:CamelizeResponse"/>
    </operation>
  </portType>
  <binding name="CamelizerCamelizerBinding" type="typens:CamelizerCamelizerPort">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>
    <operation name="Camelize">
      <soap:operation soapAction="/camelizer/api/Camelize"/>
      <input>
        <soap:body namespace="urn:ActionWebService" use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </input>
      <output>
        <soap:body namespace="urn:ActionWebService" use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </output>
    </operation>
  </binding>
  <service name="CamelizerService">
    <port name="CamelizerCamelizerPort" binding="typens:CamelizerCamelizerBinding">
      <soap:address location="http://localhost:3001/camelizer/api"/>
    </port>
  </service>
</definitions>