<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://localhost/Node" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" name="NodeDefinition" targetNamespace="http://localhost/Node">
  <types />
  <message name="NodeMessage">
    <part name="Part" type="xsd:string" />
  </message>
  <portType name="NodePortType">
    <operation name="NodeOperation">
      <input name="Input" message="tns:NodeMessage" />
      <output name="Output" message="tns:NodeMessage" />
    </operation>
  </portType>
  <binding name="NodeBinding" type="tns:NodePortType">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
    <operation name="NodeOperation">
      <soap:operation />
      <input name="Input">
        <soap:body use="literal" namespace="http://localhost/Node" />
      </input>
      <output name="Output">
        <soap:body use="literal" namespace="http://localhost/Node" />
      </output>
    </operation>
  </binding>
  <service name="NodeService">
    <port name="NodePort" binding="tns:NodeBinding">
      <soap:address location="NodeEndpoint" />
    </port>
  </service>
</definitions>

