<?xml version="1.0" encoding="UTF-8"?>
<definitions name="Joiner" xmlns:typens="urn:ActionWebService" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="urn:ActionWebService" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <message name="Join">
    <part name="string" type="xsd:string"/>
  </message>
  <message name="JoinResponse">
    <part name="return" type="xsd:string"/>
  </message>
  <portType name="JoinerJoinerPort">
    <operation name="Join">
      <input message="typens:Join"/>
      <output message="typens:JoinResponse"/>
    </operation>
  </portType>
  <binding name="JoinerJoinerBinding" type="typens:JoinerJoinerPort">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>
    <operation name="Join">
      <soap:operation soapAction="/joiner/api/Join"/>
      <input>
        <soap:body namespace="urn:ActionWebService" use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </input>
      <output>
        <soap:body namespace="urn:ActionWebService" use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </output>
    </operation>
  </binding>
  <service name="JoinerService">
    <port name="JoinerJoinerPort" binding="typens:JoinerJoinerBinding">
      <soap:address location="http://localhost:3000/joiner/api"/>
    </port>
  </service>
</definitions>