<?xml version="1.0" encoding="UTF-8"?>

<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://localhost/LeafNode"
	xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/varprop" name="LeafNodeDefinition"
	targetNamespace="http://localhost/LeafNode">


	<types/>



	<message name="LeafMessage">
		<part name="Part" element="xsd:string" />
	</message>




	<portType name="LeafPortType">
		<operation name="LeafOperation">
			<input name="Input" message="tns:LeafMessage" />
			<output name="Output" message="tns:LeafMessage" />
		</operation>
	</portType>



	<binding name="LeafBinding" type="tns:LeafPortType">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"
			style="document" />
		<operation name="LeafOperation">
			<input name="Input">
				<soap:body use="literal" />
			</input>
			<output name="Output">
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>



	<service name="LeafService">
		<port name="LeafPort" binding="tns:LeafBinding">
			<soap:address location="LeafNodeEndpoint" />
		</port>
	</service>
</definitions>

